Datasheet
-----------


* `ESP8266`_ 
* `Raspberry-Pi-Pico`_ 
* `OLED-Screen`_ 
* `Buzzer`_ 
* `DHT11`_ 
* `Relay`_ 
* `WS2812`_ 
* `LDR`_ 
* `L9110`_ 



.. _GitHub: https://github.com/Robotistan/PicoBricks
.. _ESP8266: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/ESP8266.pdf
.. _Raspberry-Pi-Pico: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/RaspberryPiPico.pdf
.. _Oled-Screen: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/SSD1306.pdf
.. _Buzzer: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/PassiveBuzzer.pdf
.. _DHT11: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/DHT11.pdf
.. _Relay: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/Relay.pdf
.. _WS2812: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/WS2812.pdf
.. _LDR: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/LDR%20.pdf
.. _L9110: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/L9110.pdf
