Datasheet
---------

* `ESP8266`_ (Datasheet)
* `Raspberry-Pi-Pico`_ (Datasheet)
* `OledScreen`_ (Datasheet)
* `Buzzer`_ (Datasheet)

.. _GitHub: https://github.com/Robotistan/PicoBricks
.. _ESP8266: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/esp8266-datasheet.pdf
.. _Raspberry-Pi-Pico: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/raspberrypico-datasheet.pdf
.. _OledScreen: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/ssd1306-datasheet.pdf
.. _Buzzer: https://github.com/Robotistan/PicoBricks/blob/main/Documents/Datasheets/passive%20buzzer-datasheet.pdf
